# Generated by Django 2.1.15 on 2024-05-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineshop', '0010_клиенты'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
